  1  CREATE TABLE EP_AC_HIST_STATISTIC (TABLE_SOURCE CHAR(16 CHAR),
  2  OBSERVATION_PERIOD                                 DATE,
  3  FILE_COUNT                                         NUMBER,
  4  CUR_PGM_NAME                                       VARCHAR2(32 CHAR),
  5  NXT_PGM_NAME                                       VARCHAR2(32 CHAR),
  6  CUR_FILE_ALIAS                                     VARCHAR2(10 CHAR),
  7  NXT_FILE_ALIAS                                     VARCHAR2(10 CHAR),
  8  WR_REC_Q                                           NUMBER,
  9  IN_REC_Q                                           NUMBER,
 10  GN_REC_Q                                           NUMBER(9),
 11  DR_REC_Q                                           NUMBER,
 12  FILE_SIZE                                          NUMBER(15),
 13  CORRECTION_FACTOR                                  NUMBER(4,2),
 14  COMMENTS                                           VARCHAR2(128 CHAR));